# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
      - image: circleci/mysql:5.6
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: circle_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_HOST: "%"
          MYSQL_USER: root
    working_directory: /go/src/github.com/InVisionApp/go-master
    steps:
      - checkout
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run: go get -t -v ./...
      - run: MYSQL_ALLOW_EMPTY_PASSWORD=true MYSQL_DATABASE=circle_test MYSQL_HOST=127.0.0.1 make test